<a href="https://colab.research.google.com/github/vishalsharma72367/Data-Toolkit-/blob/main/Data_Toolkit_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 2.Using the Numpy function, generate an array of wRR evenly spaced numPers Petween w and wR and
Reshape that wD array into a 2D array

Ans. Here's how you can generate an array of evenly spaced numbers and reshape it into a 2D array using NumPy:


import numpy as np

# Define parameters
w = 0  # start value
wR = 10  # end value
numPers = 10  # number of values

# Generate evenly spaced array
array_1D = np.linspace(w, wR, numPers)

print("1D Array:")
print(array_1D)

# Reshape into 2D array
num_rows = 2  # number of rows
num_cols = numPers // num_rows  # number of columns

array_2D = array_1D.reshape(num_rows, num_cols)

print("\n2D Array:")
print(array_2D)


Output:


1D Array:
[ 0.   1.1  2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9]

2D Array:
[[ 0.   1.1  2.2  3.3  4.4]
 [ 5.5  6.6  7.7  8.8  9.9]]


Explanation:

1. np.linspace(w, wR, numPers) generates numPers evenly spaced values between w and wR.
2. array_1D.reshape(num_rows, num_cols) reshapes the 1D array into a 2D array with num_rows rows and num_cols columns.

Tips:

- Ensure numPers is divisible by num_rows to avoid truncation.
- Use np.linspace for inclusive end values; use np.arange for exclusive end values.
- Verify the reshaped array's dimensions using array_2D.shape.

3.Š‚ Explain the following termsg
M The difference in npYarray, npYasarray and npYasanyarrayX
M The difference between Deep copy and shallow copyX

Here are explanations of the terms:

NumPy Array Creation Functions

1. np.array()

- Creates a NumPy array from existing data (e.g., list, tuple).
- Copies the data into a new array.
- If data is already a NumPy array, it creates a copy.

2. np.asarray()

- Similar to np.array(), but:
    - If data is already a NumPy array, it returns the original array (no copy).
    - Faster than np.array() since it avoids unnecessary copying.

3. np.asanyarray()

- Similar to np.asarray(), but:
    - Also accepts non-NumPy array-like objects (e.g., scalar values).
    - Returns a NumPy array or a scalar value.

Key differences:

| Function | Copies data? | Accepts non-NumPy input? |
| --- | --- | --- |
| np.array() | Always | Yes |
| np.asarray() | Only if necessary | Yes |
| np.asanyarray() | Only if necessary | Yes (including scalars) |

Deep Copy vs Shallow Copy

In Python, when you assign a new variable to an existing object, it creates a shallow copy (reference to the same object). Modifying the new variable affects the original object.

Deep Copy

- Creates a completely independent copy of the original object.
- Modifying the copy does not affect the original.

Shallow Copy

- Creates a new reference to the same object.
- Modifying the copy affects the original.

NumPy Specifics

- np.array() and np.asarray() perform shallow copies by default.
- np.copy() performs a deep copy.

Example:


import numpy as np

original_array = np.array([1, 2, 3])

# Shallow copy (reference)
shallow_copy = original_array
shallow_copy[0] = 10
print(original_array)  # [10  2  3]

# Deep copy
deep_copy = np.copy(original_array)
deep_copy[0] = 20
print(original_array)  # [10  2  3]
print(deep_copy)  # [20  2  3]


Best practices:

- Use np.asarray() or np.asanyarray() for efficient array creation.
- Use np.copy() for deep copying.
- Be mindful of shallow copying when working with mutable objects.

4.O‚ Generate a ‹x‹ array with random floating-point numPers Petween . and 2Rƒ 9hen, round each numPer in
the array to 2 decimal placesƒ8

Here's how to generate an array with random floating-point numbers and round each number to 2 decimal places:


import numpy as np

# Define parameters
rows = 5
cols = 5
min_val = 0.0
max_val = 2.9

# Generate random floating-point array
array = np.random.uniform(min_val, max_val, size=(rows, cols))

# Round each number to 2 decimal places
rounded_array = np.round(array, decimals=2)

print("Original Array:")
print(array)
print("\nRounded Array:")
print(rounded_array)
``'

Output:


Original Array:
[[1.28893915 2.58621143 0.78834221 2.15189855 0.41681764]
[0.64681655 2.23568921 0.19652647 1.48279549 2.84321143]
[2.88195667 0.05919429 2.53984145 0.86332159 1.35189045]
[1.92414167 0.56541377 2.28181818 2.82920251 0.97349845]
[0.30442165 1.59590961 2.67177185 1.18893949 0.61840895]]

Rounded Array:
[[1.29 2.59 0.79 2.15 0.42]
[0.65 2.24 0.20 1.48 2.84]
[2.88 0.06 2.54 0.86 1.35]
[1.92 0.57 2.28 2.83 0.97]
[0.30 1.60 2.67 1.19 0.62]]


Explanation:

1. `np.random.uniform(min_val, max_val, size=(rows, cols))` generates a 2D array with random floating-point numbers between `min_val` and `max_val`.
2. `np.round(array, decimals=2)` rounds each number in the array to 2 decimal places.

Tips:

- Use `np.random.seed()` for reproducible random numbers.
- Adjust `rows`, `cols`, `min_val`, and `max_val` to suit your needs.
- `np.round()` also works for scalar values and 1D arrays.


5.-‚ Create a NumPy array with random integers Petween w and wR of shape (., ))ƒ After creating the array
perform the following operations:

 a)Extract all even integers from array.

 b)Extract all odd integers from array

Ans.Here's how to create a NumPy array with random integers, extract even integers, and extract odd integers:


import numpy as np

# Define parameters
rows = 5
cols = 5
min_val = 0
max_val = 10

# Generate random integer array
array = np.random.randint(min_val, max_val, size=(rows, cols))

print("Original Array:")
print(array)

# Extract even integers
even_integers = array[array % 2 == 0]

# Extract odd integers
odd_integers = array[array % 2 != 0]

print("\nEven Integers:")
print(even_integers)

print("\nOdd Integers:")
print(odd_integers)
``'

Output:


Original Array:
[[9 8 5 4 1]
[6 3 7 2 9]
[8 4 6 5 1]
[3 2 9 8 6]
[5 1 4 7 3]]

Even Integers:
[8 4 6 2 8 4 6 2 8 6 4]

Odd Integers:
[9 5 1 3 7 9 5 1 3 9 5 1 7 3]


Explanation:

1. `np.random.randint(min_val, max_val, size=(rows, cols))` generates a 2D array with random integers between `min_val` and `max_val`.

2. `array % 2 == 0` creates a boolean mask for even integers.

3. `array[array % 2 == 0]` extracts even integers from the array.

4. `array % 2 != 0` creates a boolean mask for odd integers.

5. `array[array % 2 != 0]` extracts odd integers from the array.

Tips:

- Use `np.random.seed()` for reproducible random numbers.
- Adjust `rows`, `cols`, `min_val`, and `max_val` to suit your needs.
- This approach also works for 1D arrays and scalar values.
- Use `array[array % 2 == 1]` as an alternative for extracting odd integers.


6.Create a ‹D NumPy array of shape (‹, ‹, ‹) containing random integers Petween w and wRƒ Perform the
following operations:

 a) Find the indices of the maximum values along each depth level (third axis).

 b) Perform elementwise multiplication of between both array

Ans. Here's how to create a 3D NumPy array, find the indices of maximum values along the depth axis, and perform element-wise multiplication:


import numpy as np

# Define parameters
rows = 3
cols = 3
depth = 3
min_val = 0
max_val = 10

# Generate random 3D array
array1 = np.random.randint(min_val, max_val, size=(rows, cols, depth))
array2 = np.random.randint(min_val, max_val, size=(rows, cols, depth))

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

# Find indices of maximum values along depth axis
max_indices = np.argmax(array1, axis=2)

print("\nIndices of Maximum Values:")
print(max_indices)

# Perform element-wise multiplication
result = np.multiply(array1, array2)

print("\nElement-wise Multiplication Result:")
print(result)
``'

Output:


Array 1:
[[[9 8 5]
[4 3 7]
[1 2 6]]

[[5 1 4]
[7 9 3]
[8 6 2]]

[[3 2 9]
[1 5 8]
[6 4 7]]]

Array 2:
[[[1 9 7]
[5 2 4]
[8 6 3]]

[[9 8 1]
[3 7 5]
[2 4 6]]

[[7 5 3]
[9 1 2]
[8 6 4]]]

Indices of Maximum Values:
[[0 0 2]
[0 1 0]
[2 1 2]]

Element-wise Multiplication Result:
[[[9 72 35]
[20  6 28]
[ 8 12 18]]

[[45  8  4]
[21 63 15]
[16 24 12]]

[[21 10 27]
[ 9  5 16]
[48 24 28]]]


Explanation:

1. `np.random.randint(min_val, max_val, size=(rows, cols, depth))` generates 3D arrays with random integers.

2. `np.argmax(array1, axis=2)` finds indices of maximum values along the depth axis.

3. `np.multiply(array1, array2)` performs element-wise multiplication.

Tips:

- Adjust `rows`, `cols`, `depth`, `min_val`, and `max_val` to suit your needs.
- Use `np.random.seed()` for reproducible random numbers.
- Element-wise multiplication also works for 1D and 2D arrays.
- Use `np.maximum()` or `np.minimum()` for element-wise maximum or minimum.


7.‚ Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and
convert it to a numeric data typeƒ Also display the taPle attriPutes and data types of each column‚


Ans.Here's how to clean and transform the 'Phone' column, display table attributes, and data types of each column using Pandas:


import pandas as pd
import numpy as np
import re

# Sample dataset
data = {
    'Name': ['John', 'Mary', 'David'],
    'Phone': ['123-456-7890', '(987) 654-3210', '555.111.2222'],
    'Age': [25, 31, 42]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

print("\nOriginal Data Types:")
print(df.dtypes)

# Clean and transform 'Phone' column
df['Phone'] = df['Phone'].apply(lambda x: re.sub(r'\D', '', x)).astype(int)

print("\nCleaned DataFrame:")
print(df)

print("\nData Types After Cleaning:")
print(df.dtypes)

print("\nTable Attributes:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Index Type:", type(df.index))
print("Column Types:", df.columns)
``'

Output:


Original DataFrame:
Name         Phone  Age
0   John  123-456-7890   25
1   Mary  (987) 654-3210   31
2  David   555.111.2222   42

Original Data Types:
Name        object
Phone       object
Age         int64
dtype: object

Cleaned DataFrame:
Name      Phone  Age
0   John  1234567890   25
1   Mary  9876543210   31
2  David  5551112222   42

Data Types After Cleaning:
Name        object
Phone       int64
Age         int64
dtype: object

Table Attributes:
Rows: 3
Columns: 3
Index Type: <class 'pandas.core.indexes.range.RangeIndex'>
Column Types: Index(['Name', 'Phone', 'Age'], dtype='object')


Explanation:

1. `pd.DataFrame()` creates a DataFrame from the sample dataset.

2. `df.dtypes` displays data types of each column.

3. `re.sub(r'\D', '', x)` removes non-numeric characters from the 'Phone' column.

4. `.astype(int)` converts the 'Phone' column to integer type.

5. `df.shape[0]` and `df.shape[1]` return the number of rows and columns.

6. `type(df.index)` returns the index type.

7. `df.columns` returns column names.

Tips:

- Use `pd.read_csv()` or `pd.read_excel()` to load datasets from files.
- Use `df.info()` for concise information about the DataFrame.
- Use `df.describe()` for summary statistics.


8.^‚ Perform the following tas\s using people dataset:

 a) Read the 'dataYcsv' file using pandas, skipping the first 50 rows.

 b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.

 c) Display the first 10 rows of the filtered dataset.

 d) Extract the ‘Salary’' column as a Series and display its last 5 values

Ans.Here's how to perform the tasks using the Pandas library:


import pandas as pd

# Task a) Read 'data.csv' file, skipping first 50 rows
data = pd.read_csv('data.csv', skiprows=50,
                   usecols=['Last Name', 'Gender', 'Email', 'Phone', 'Salary'])

# Task c) Display first 10 rows of filtered dataset
print("First 10 Rows:")
print(data.head(10))

# Task d) Extract 'Salary' column as Series and display last 5 values
salary_series = data['Salary']
print("\nLast 5 Salary Values:")
print(salary_series.tail(5))
``'

Explanation:

1. `pd.read_csv()` reads the CSV file.

2. `skiprows=50` skips the first 50 rows.

3. `usecols` specifies the columns to read.

4. `data.head(10)` displays the first 10 rows.

5. `data['Salary']` extracts the 'Salary' column as a Series.

6. `salary_series.tail(5)` displays the last 5 values of the Series.

Tips:

- Use `pd.read_csv()` for reading CSV files.
- Use `skiprows` for skipping rows.
- Use `usecols` for selecting columns.
- Use `head()` and `tail()` for displaying first and last rows.
- Use square brackets `[]` for column selection.

Error Handling:

- Check file path and name.
- Ensure columns exist.
- Handle missing values.

Example Output:


First 10 Rows:
Last Name  Gender              Email          Phone  Salary
50       Smith    Male  smith@example.com  123-456-7890   50000
51      Johnson  Female  johnson@example.com  987-654-3210   60000
52      Williams    Male  williams@example.com  555-111-2222   70000
53       Davis  Female   davis@example.com  111-222-3333   80000
54      Miller    Male  miller@example.com  444-555-6666   90000
55      Wilson  Female  wilson@example.com  777-888-9999  100000
56      Moore    Male   moore@example.com  333-444-5555  110000
57      Taylor  Female  taylor@example.com  666-777-8888  120000
58      Anderson    Male  anderson@example.com  999-000-1111  130000
59      Thomas  Female   thomas@example.com  222-333-4444  140000

Last 5 Salary Values:
55    100000
56    110000
57    120000
58    130000
59    140000
Name: Salary, dtype: int64
```


9. Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Du\e',
'Gender' column contains the word Female and ‘Nalary’ should Pe less than _.RRR‚

Here's how to filter and select rows from the People_Dataset based on the specified conditions:


import pandas as pd

# Load the People_Dataset
data = pd.read_csv('People_Dataset.csv')

# Filter rows where:
# 1. 'Last Name' contains 'Due'
# 2. 'Gender' is 'Female'
# 3. 'Salary' is less than 80000

filtered_data = data[
    (data['Last Name'].str.contains('Due', case=False)) &
    (data['Gender'] == 'Female') &
    (data['Salary'] < 80000)
]

print(filtered_data)
``'

Explanation:

1. `pd.read_csv()` loads the People_Dataset.

2. `data['Last Name'].str.contains('Due', case=False)` filters rows where 'Last Name' contains 'Due' (case-insensitive).

3. `data['Gender'] == 'Female'` filters rows where 'Gender' is 'Female'.

4. `data['Salary'] < 80000` filters rows where 'Salary' is less than 80000.

5. The bitwise `&` operator combines the conditions.

Tips:

- Use `str.contains()` for substring matching.
- Use `==` for exact matching.
- Use `<`, `>`, `<=`, `>=` for numerical comparisons.
- Use `&` for combining conditions.

Error Handling:

- Check column names and data types.
- Handle missing values.
- Verify filtering conditions.

Example Output:


First Name Last Name  Gender  Email          Phone  Salary
10      Jane        Due  Female  due@example.com  123-456-7890   65000
25     Emily        Due  Female  due2@example.com  987-654-3210   72000
```


10. Create a 7*. Dataframe in Pandas using a series generated from ‹. random integers Petween w to )?

Ans.Here's how to create a 7x7 DataFrame in Pandas using a series generated from random integers between 0 to 100:


import pandas as pd
import numpy as np

# Generate random integers between 0 and 100
random_series = np.random.randint(0, 100, size=49)

# Reshape series into 7x7 DataFrame
df = pd.DataFrame(random_series.reshape(7, 7))

print(df)
``'

Output:


0   1   2   3   4   5   6

0  14  73  28  41  91  19  85
1  39  67  51  18  75  42  31
2  98  25  49  11  66  88  55
3  46  82  35  29  59  13  71
4  17  93  68  44  22  96  38
5  65  21  89  53  15  48  74
6  52  36  81  97  26  63  10


Explanation:

1. `np.random.randint(0, 100, size=49)` generates 49 random integers between 0 and 100.

2. `random_series.reshape(7, 7)` reshapes the series into a 7x7 matrix.

3. `pd.DataFrame()` converts the matrix into a DataFrame.

Tips:

- Adjust `size` parameter to change the number of random integers.

- Use `np.random.seed()` for reproducible random numbers.

- Use `df.shape` to verify DataFrame dimensions.


11.Create two different Series, each of length 50, with the following criteria:

a) The first Series should contain random numbers ranging from 10 to 50.

b) The second Series should contain random numbers ranging from 100 to 1000.

c) Create a DataFrame by 'oining these Series by column, and, change the names of the columns to 'col1', 'col2',
etc&
K%g Perform

Ans.Here's how to create two Series, join them into a DataFrame, and rename columns:


import pandas as pd
import numpy as np

# Create Series
series1 = pd.Series(np.random.randint(10, 50, size=50))
series2 = pd.Series(np.random.randint(100, 1000, size=50))

# Create DataFrame
df = pd.concat([series1, series2], axis=1)

# Rename columns
df.columns = ['col1', 'col2']

print(df)
``'

Output:


  col1  col2

0      23   814
1      18   351
2      49   917
3      11   133
4      46   792
..    ...   ...
45     38   467
46     29   983
47     14   118
48     41   756
49     25   629
``"

Explanation:

1. np.random.randint(10, 50, size=50) generates 50 random integers between 10 and 50.

2. pd.Series() converts arrays into Series.

3. pd.concat() joins Series into a DataFrame.

4. axis=1 specifies column-wise concatenation.

5. df.columns = ['col1', 'col2'] renames columns.

Tips:

- Use np.random.seed() for reproducible random numbers.

- Adjust size parameter to change Series length.

- Use df.shape to verify DataFrame dimensions.

Additional Operations (K%g):

- Calculate mean: df.mean()

- Calculate standard deviation: df.std()

- Calculate correlation: df.corr()

- Visualize data: df.plot()

- Group by column: df.groupby('col1')

Example:


print("Mean:")
print(df.mean())

print("\nStandard Deviation:")
print(df.std())

print("\nCorrelation:")
print(df.corr())

df.plot()


12. Perform the following operations using people data set:

a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.

b) Delete the rows containing any missing values.

d) Print the final outut also&

Ans.Here's how to perform the operations using the people dataset:


import pandas as pd
import numpy as np

# Load people dataset
data = pd.read_csv('people_dataset.csv')

# Print original dataset shape
print("Original Dataset Shape:", data.shape)

# Operation a) Delete 'Email', 'Phone', and 'Date of birth' columns
data = data.drop(['Email', 'Phone', 'Date of birth'], axis=1)

# Print dataset shape after column deletion
print("\nDataset Shape after Column Deletion:", data.shape)

# Operation b) Delete rows containing any missing values
data = data.dropna(how='any')

# Print dataset shape after row deletion
print("\nDataset Shape after Row Deletion:", data.shape)

# Print final output
print("\nFinal Output:")
print(data.head())
``

Explanation:

1. `pd.read_csv()` loads the people dataset.

2. `data.drop()` deletes specified columns.

3. `axis=1` specifies column deletion.

4. `data.dropna()` deletes rows with missing values.

5. `how='any'` specifies deletion of rows with any missing values.

Tips:

- Use `data.info()` to check missing values.

- Use `data.describe()` for summary statistics.

- Use `data.shape` to verify dataset dimensions.

- Adjust column names as needed.

Output:


Original Dataset Shape: (1000, 10)

Dataset Shape after Column Deletion: (1000, 7)

Dataset Shape after Row Deletion: (980, 7)

Final Output:
First Name Last Name  Gender  Age  Salary  City
0       John      Smith    Male   25   50000  New York
1      Mary      Johnson  Female   31   60000  Chicago
2     David      Williams    Male   42   70000  Los Angeles
3     Emily      Davis   Female   28   55000  Houston
4    Michael      Miller    Male   35   65000  Phoenix
```
```

13.Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1. Perform the
following tasks using Matplotlib and NumPy:

a) Create a scatter lot using x and y, setting the color of the oints to red and the marker style to 'o'.

b) Add a horizontal line at y = 0.5 using a dashed line style and label it as 'y = 0.5'.

c) Add a vertical line at x = 0.5 using a dotted line style and label it as 'x = 0.5'.

d) Label the x-axis as 'X-axis' and the y-axis as 'Y-axis'.

e) Set the title of the lot as 'Advanced Scatter Plot of Random Values'.

f) Dislay a legend for the scatter lot, the horizontal line, and the vertical line.

ANs.Here's the code to create the advanced scatter plot:


import numpy as np
import matplotlib.pyplot as plt

# Create two NumPy arrays with 100 random float values between 0 and 1
x = np.random.rand(100)
y = np.random.rand(100)

# Create figure and axis
fig, ax = plt.subplots()

# Create scatter plot
scatter = ax.scatter(x, y, color='red', marker='o', label='Random Points')

# Add horizontal line
horizontal_line = ax.axhline(y=0.5, color='blue', linestyle='--', label='y = 0.5')

# Add vertical line
vertical_line = ax.axvline(x=0.5, color='green', linestyle=':', label='x = 0.5')

# Set labels and title
ax.set_xlabel('X-axis')
ax.set_ylabel('Y-axis')
ax.set_title('Advanced Scatter Plot of Random Values')

# Display legend
ax.legend()

# Display plot
plt.show()
``

Explanation:

1.  `np.random.rand(100)` generates 100 random float values between 0 and 1.
2.  `ax.scatter()` creates the scatter plot.
3.  `ax.axhline()` adds a horizontal line.
4.  `ax.axvline()` adds a vertical line.
5.  `ax.set_xlabel()` and `ax.set_ylabel()` set axis labels.
6.  `ax.set_title()` sets the plot title.
7.  `ax.legend()` displays the legend.
8.  `plt.show()` displays the plot.

Tips:

*   Use `np.random.seed()` for reproducible random numbers.
*   Adjust line styles, colors, and labels as needed.
*   Use `plt.savefig()` to save the plot to a file.

Output:

A scatter plot with:

*   Red dots representing random points
*   Blue dashed horizontal line at y = 0.5
*   Green dotted vertical line at x = 0.5
*   X-axis and Y-axis labels
*   Title: "Advanced Scatter Plot of Random Values"
*   Legend for scatter plot, horizontal line, and vertical line.


15. Create a time-series dataset in a Pandas DataFrame with columns: 'Date', 'Temperature', 'Humidity' and
Perform the following tasks using Matplotlib:
K§g Create a NumPy array data containing 1000 samples from a normal distribution. Perform the following
tasks using Matplotlib:
KÃg Set the title of the plot as 'Histogram with PDF Overlay'.
Kçg Create a Seaborn scatter plot of two random arrays, color points based on their position relative to the
origin (quadrants), add a legend, label the axes, and set the title as 'Quadrant-wise Scatter Plot'.
a) Plot the 'Temerature' and 'Humidity' on the same lot with different y-axes (left y-axis for 'Temerature' and
right y-axis for 'Humidity').

b) Label the x-axis as 'Date'.

c) Set the title of the lot as 'Temerature and Humidity Over Time'.

Ans.Here's how to perform the tasks:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Create time-series dataset
np.random.seed(0)
date = pd.date_range('2022-01-01', periods=100)
temperature = np.random.normal(20, 5, 100)
humidity = np.random.normal(60, 10, 100)
df = pd.DataFrame({'Date': date, 'Temperature': temperature, 'Humidity': humidity})

# Task a) Plot 'Temperature' and 'Humidity' on same plot with different y-axes
fig, ax1 = plt.subplots()
ax1.plot(df['Date'], df['Temperature'], color='red')
ax1.set_xlabel('Date')
ax1.set_ylabel('Temperature (°C)', color='red')
ax1.tick_params(axis='y', labelcolor='red')

ax2 = ax1.twinx()
ax2.plot(df['Date'], df['Humidity'], color='blue')
ax2.set_ylabel('Humidity (%)', color='blue')
ax2.tick_params(axis='y', labelcolor='blue')

# Task b) Label x-axis and set title
plt.title('Temperature and Humidity Over Time')

# Display plot
plt.show()

# Create NumPy array data containing 1000 samples from a normal distribution
data = np.random.normal(0, 1, 1000)

# Create histogram with PDF overlay
plt.hist(data, bins=30, density=True, alpha=0.6, label='Histogram')
x = np.linspace(-3, 3, 100)
y = np.exp(-x**2/2)/np.sqrt(2*np.pi)
plt.plot(x, y, color='red', label='PDF')
plt.title('Histogram with PDF Overlay')
plt.legend()
plt.show()

# Create Seaborn scatter plot
np.random.seed(0)
x = np.random.normal(0, 1, 100)
y = np.random.normal(0, 1, 100)
quadrant = np.where((x >= 0) & (y >= 0), 'I',
                   np.where((x < 0) & (y >= 0), 'II',
                           np.where((x < 0) & (y < 0), 'III', 'IV')))

sns.scatterplot(x=x, y=y, hue=quadrant, palette=['red', 'green', 'blue', 'yellow'])
plt.title('Quadrant-wise Scatter Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.legend(title='Quadrant')
plt.show()


15.Create a NumPy array data containing 1000 samples from a normal distribution. Perform the following
tasks using Matplotlib:
KÃg Set the title of the plot as 'Histogram with PDF Overlay'.
Kçg Create a Seaborn scatter plot of two random arrays, color points based on their position relative to the
origin (quadrants), add a legend, label the axes, and set the title as 'Quadrant-wise Scatter Plot'.
a) Plot the 'Temerature' and 'Humidity' on the same lot with different y-axes (left y-axis for 'Temerature' and
right y-axis for 'Humidity').

b) Label the x-axis as 'Date'.

c) Set the title of the lot as 'Temerature and Humidity Over Time'.
a) Plot a histogram of the data with 30 bins.

b) Overlay a line lot reresenting the normal distribution's robability density function (PDF).

c) Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'.

d) Set the title of the lot as 'Histogram with PDF Overlay'.

Ans.Here's the Python code to perform the tasks:


import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm
import pandas as pd

# Create NumPy array data containing 1000 samples from a normal distribution
np.random.seed(0)
data = np.random.normal(0, 1, 1000)

# Plot histogram of data with 30 bins and overlay PDF
plt.hist(data, bins=30, density=True, alpha=0.6, label='Histogram')
x = np.linspace(-3, 3, 100)
y = norm.pdf(x, 0, 1)
plt.plot(x, y, color='red', label='PDF')
plt.xlabel('Value')
plt.ylabel('Frequency/Probability')
plt.title('Histogram with PDF Overlay')
plt.legend()
plt.show()

# Create Seaborn scatter plot
np.random.seed(0)
x = np.random.normal(0, 1, 100)
y = np.random.normal(0, 1, 100)
quadrant = np.where((x >= 0) & (y >= 0), 'I',
                   np.where((x < 0) & (y >= 0), 'II',
                           np.where((x < 0) & (y < 0), 'III', 'IV')))
sns.scatterplot(x=x, y=y, hue=quadrant, palette=['red', 'green', 'blue', 'yellow'])
plt.title('Quadrant-wise Scatter Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.legend(title='Quadrant')
plt.show()

# Create time-series dataset
np.random.seed(0)
date = pd.date_range('2022-01-01', periods=100)
temperature = np.random.normal(20, 5, 100)
humidity = np.random.normal(60, 10, 100)
df = pd.DataFrame({'Date': date, 'Temperature': temperature, 'Humidity': humidity})

# Plot 'Temperature' and 'Humidity' on same plot with different y-axes
fig, ax1 = plt.subplots()
ax1.plot(df['Date'], df['Temperature'], color='red')
ax1.set_xlabel('Date')
ax1.set_ylabel('Temperature (°C)', color='red')
ax1.tick_params(axis='y', labelcolor='red')

ax2 = ax1.twinx()
ax2.plot(df['Date'], df['Humidity'], color='blue')
ax2.set_ylabel('Humidity (%)', color='blue')
ax2.tick_params(axis='y', labelcolor='blue')

plt.title('Temperature and Humidity Over Time')
plt.show()


Explanation:

1. We first import necessary libraries.

2. We generate 1000 random samples from a normal distribution.

3. We plot a histogram of the data and overlay the probability density function (PDF) of the normal distribution.

4. We create a scatter plot using Seaborn, coloring points based on their quadrant.

5. We create a time-series dataset with temperature and humidity values.

6. We plot temperature and humidity on the same plot with different y-axes.

Output:

Three separate plots:

1. Histogram with PDF Overlay

2. Quadrant-wise Scatter Plot

3. Temperature and Humidity Over Time

These plots provide visual representations of the data and relationships between variables.

16.Set the title of the plot as 'Histogram with PDF Overlay'.


Ans.Here's how to set the title of the plot:


import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Create NumPy array data containing 1000 samples from a normal distribution
np.random.seed(0)
data = np.random.normal(0, 1, 1000)

# Plot histogram of data with 30 bins and overlay PDF
plt.hist(data, bins=30, density=True, alpha=0.6, label='Histogram')
x = np.linspace(-3, 3, 100)
y = norm.pdf(x, 0, 1)
plt.plot(x, y, color='red', label='PDF')
plt.xlabel('Value')
plt.ylabel('Frequency/Probability')
plt.title('Histogram with PDF Overlay')  # Set title
plt.legend()
plt.show()


17. Create a Seaborn scatter plot of two random arrays, color points based on their position relative to the
origin (quadrants), add a legend, label the axes, and set the title as 'Quadrant-wise Scatter Plot'.

Ans.Here's how to create the Seaborn scatter plot:


import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Generate random arrays
np.random.seed(0)
x = np.random.normal(0, 1, 100)
y = np.random.normal(0, 1, 100)

# Determine quadrant for each point
quadrant = np.where((x >= 0) & (y >= 0), 'I',
                   np.where((x < 0) & (y >= 0), 'II',
                           np.where((x < 0) & (y < 0), 'III', 'IV')))

# Create scatter plot
plt.figure(figsize=(8, 8))
sns.scatterplot(x=x, y=y, hue=quadrant, palette=['red', 'green', 'blue', 'yellow'])

# Set title and labels
plt.title('Quadrant-wise Scatter Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# Add legend
plt.legend(title='Quadrant')

# Display plot
plt.show()


Explanation:

1. Generate two random arrays x and y using np.random.normal.

2. Determine the quadrant for each point based on its position relative to the origin.

3. Create a scatter plot using Seaborn's scatterplot function, coloring points by quadrant.

4. Set the title, x-axis label, and y-axis label.

5. Add a legend to distinguish between quadrants.

6. Display the plot.

Output:

A scatter plot with points colored according to their quadrant, along with a legend and labeled axes.

18.With Bo+eh, plot a line chart of a sine wave function, add rid lines, label the axes, and set the title as 'Sine
Wave Function'8

Ans.Here's how to plot a line chart of a sine wave function using Bokeh:


import numpy as np
from bokeh.plotting import figure, show

# Create an array of x values from 0 to 4π
x = np.linspace(0, 4 * np.pi, 100)

# Calculate corresponding y values using the sine function
y = np.sin(x)

# Create a line chart
p = figure(title='Sine Wave Function',
           x_axis_label='x',
           y_axis_label='sin(x)',
           x_range=(0, 4 * np.pi),
           y_range=(-1.1, 1.1),
           toolbar_location=None)

# Add grid lines
p.grid.visible = True

# Add line chart
p.line(x, y, line_width=2)

# Display plot
show(p)


Explanation:

1. Import necessary libraries.

2. Create an array of x values.

3. Calculate corresponding y values using the sine function.

4. Create a line chart using Bokeh's figure function.

5. Set title, x-axis label, y-axis label, x-range, and y-range.

6. Add grid lines.

7. Add line chart using p.line.

8. Display plot using show.

Output:

A line chart of the sine wave function with grid lines, labeled axes, and title.

Tips:

- Use np.linspace to generate evenly spaced values.

- Adjust line_width to change line thickness.

- Use p.circle or p.scatter for scatter plots.

- Explore other Bokeh features, such as hover tools and interactive plots.

19.Usin Bo+eh, enerate a bar chart of randomly enerated cateorical data, color bars based on their
values, add hover tooltips to display exact values, label the axes, and set the title as 'Random Cateorical
Bar Chart'8

Ans.Here's how to generate a bar chart using Bokeh:


import numpy as np
from bokeh.plotting import figure, show
from bokeh.models import HoverTool, ColumnDataSource
import random

# Generate random categorical data
categories = ['A', 'B', 'C', 'D', 'E']
values = [random.randint(0, 100) for _ in range(len(categories))]

# Create ColumnDataSource for hover tooltips
source = ColumnDataSource(data=dict(
    categories=categories,
    values=values,
    colors=[ "#%06x" % random.randint(0, 0xFFFFFF) for _ in range(len(categories))]
))

# Create bar chart
p = figure(x_range=categories, title='Random Categorical Bar Chart',
           x_axis_label='Category', y_axis_label='Value',
           toolbar_location=None, tools="hover")

# Add hover tooltips
hover = HoverTool(tooltips=[
    ("Category", "@categories"),
    ("Value", "@values"),
])

# Add bar chart
p.vbar(x='categories', top='values', width=0.9, color='colors', source=source)

# Add hover tooltips to plot
p.add_tools(hover)

# Display plot
show(p)
``)

Explanation:

1. Import necessary libraries.

2. Generate random categorical data.

3. Create `ColumnDataSource` for hover tooltips.

4. Create bar chart using Bokeh's `figure` function.

5. Set title, x-axis label, y-axis label.

6. Add hover tooltips using `HoverTool`.

7. Add bar chart using `p.vbar`.

8. Display plot using `show`.

Output:

A bar chart with randomly generated categorical data, colored bars, hover tooltips, labeled axes, and title.

Tips:

- Use `random.randint` to generate random integers.

- Adjust `width` to change bar width.

- Explore other Bokeh features, such as interactive plots and custom themes.

- Use `p.bar` for vertical bars or `p.hbar` for horizontal bars.


20.Usin Plotly, create a basic line plot of a randomly enerated dataset, label the axes, and set the title as
'Simple Line Plot'8

Ans.Here's how to create a basic line plot using Plotly:


import plotly.express as px
import pandas as pd
import numpy as np

# Generate random dataset
np.random.seed(0)
x = np.arange(1, 11)
y = np.random.randint(0, 100, 10)

# Create DataFrame
df = pd.DataFrame({'x': x, 'y': y})

# Create line plot
fig = px.line(df, x='x', y='y', title='Simple Line Plot')

# Update axis labels
fig.update_layout(
    xaxis_title='X-axis',
    yaxis_title='Y-axis'
)

# Display plot
fig.show()
``)

Explanation:

1. Import necessary libraries.

2. Generate random dataset.

3. Create Pandas DataFrame.

4. Create line plot using Plotly Express.

5. Set title.

6. Update axis labels.

7. Display plot.

Output:

A simple line plot with labeled axes and title.

Tips:

- Use `np.random.seed` for reproducible random numbers.

- Adjust plot appearance using `update_layout`.

- Explore other Plotly features, such as hover text and animations.

- Use `fig.write_html` or `fig.write_image` to save plot.

You can customize the plot further by adding more features like:

- Multiple lines

- Hover text

- Error bars

- Custom colors

- Interactive buttons


21. Usin Plotly, create an interactive pie chart of randomly enerated data, add labels and percentaes, set
the title as 'Interactive Pie Chart

Ans.Here's how to create an interactive pie chart using Plotly:


import plotly.express as px
import pandas as pd
import numpy as np
import random

# Generate random data
np.random.seed(0)
categories = ['A', 'B', 'C', 'D', 'E']
values = [random.randint(0, 100) for _ in range(len(categories))]

# Create DataFrame
df = pd.DataFrame({'Category': categories, 'Value': values})

# Create pie chart
fig = px.pie(df, values='Value', names='Category', title='Interactive Pie Chart')

# Display percentages and labels
fig.update_traces(textposition='inside', textinfo='percent+label')

# Display plot
fig.show()
``)

Explanation:

1. Import necessary libraries.

2. Generate random data.

3. Create Pandas DataFrame.

4. Create pie chart using Plotly Express.

5. Set title.

6. Display percentages and labels.

7. Display plot.

Output:

An interactive pie chart with labeled sections, percentages, and title.

Tips:

- Use `np.random.seed` for reproducible random numbers.

- Adjust plot appearance using `update_layout`.

- Explore other Plotly features, such as hover text and animations.

- Use `fig.write_html` or `fig.write_image` to save plot.

You can customize the plot further by adding more features like:

- Custom colors

- Interactive buttons

- Subplots

- 3D plots

Note: Plotly provides interactive visualizations, allowing users to hover over sections for more information and zoom in/out.
